### ISSUE TITLE
Display warning and critical treshholds

### ISSUE THREAD

**Issue by TheBigLee** [philiphoy/icingaweb2-module-graphite#10]
Hi

Currently the warning and critical treshholds are not displayed on the graphs.

Would it be possible to add this functionality as well?
The format url string to add is something like this:
&target=alias(color(constantLine($warning_value),'yellow'),'warning')&target=alias(color(constantLine($critical_value),'red'),'critical').

My PHP knowledge is very limited so I can't do it myself.

Thanks

**Comment by philiphoy** [comment]
@Bigluu I have added graphite argument templating. Add something like this to your config .ini

```
graphite_args_template = "target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=300&height=120&hideAxes=true&ineWidth=2&hideLegend=true&colorList=049BAF"

graphite_large_args_template = "target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=800&height=700&colorList=049BAF&lineMode=connected"
```

**Comment by TheBigLee** [comment]
@philiphoy Wow that was quick. Thanks a lot for this feature. It works perfectly.

**Comment by philiphoy** [comment]
No problem @Bigluu, i wanted to allow users to configure the graphite args, your request spurred it on.
