### ISSUE TITLE
Icingaweb 2 and Graphite module security

### ISSUE THREAD

**Issue by talbaror** [philiphoy/icingaweb2-module-graphite#12]
Hi 

I have monitoring system installed along with Graphite all works fine , but i have complains that getting into graphite initial page (below image)and consulting graphs metrics without any password is not desired.
My thought was to make initial Graphite page using Apache2 authentication will be enough along with https , but i know if i will do it Icingaweb2 will ask user password to be able visualize graphs.
So my question for you guys ,is there a way to secure initial Graphite page and to work seamless integration with Icingaweb2?
Thanks
![1](https://cloud.githubusercontent.com/assets/4032962/9011636/20e334ba-37b7-11e5-9074-7849339691cc.png)

**Comment by philiphoy** [comment]
You should be able to allow the render endpoint used by the plug in to be auth free but the graphite site insist on credentials. Something like this might work

``` xml
<Location />
  AuthType basic
  AuthName "Top Secret Beta!"
  AuthUserFile /etc/httpd/htpasswd.beta
  Require valid-user
</Location>

<Location /render>
   Allow from all
   Satisfy Any
</Location>
```

**Comment by talbaror** [comment]
Thanks :-)
