### ISSUE TITLE
Update for latest icinga2 master brunch

### ISSUE THREAD

**Issue by olfway** [philiphoy/icingaweb2-module-graphite#16]
Graphite schema changed with recent commit
https://github.com/Icinga/icinga2/commit/b10cb8a2e7acccc285377f72fef533ab277f2ad1#diff-fd8634adc3e7216fc4ecb345caba5cab

example config should be changed to something like this:
host_name_template = "$host.name$.host.$host.check_command$.perfdata"
service_name_template = "$host.name$.services.$service.name$.$service.check_command$.perfdata"
graphite_args_template = "&target=$target$.value&source=0&width=300&height=120&hideAxes=true&lineWidth=2&hideLegend=true&colorList=049BAF"
graphite_large_args_template = "&target=alias(color($target$.warn,'yellow'),'warning')&target=alias(color($target$.crit,'red'),'critical')&target=$target$.value&source=0&width=800&height=700&c

also, escape function should be updated too:
'-' not replaced now and '::' should be replaced with '_'

**Comment by philiphoy** [comment]
Thanks for the heads up @olfway. A pull request would be cool if you have the time,
