### ISSUE TITLE
Get "call to undefined method Icinga\Application\Config::getSection()" after activating graphite module

### ISSUE THREAD

**Issue by technik-werner** [philiphoy/icingaweb2-module-graphite#17]
Hi,

I've just installed the icingaweb2-graphite-module. After activating the module I'm unable to show service details in Icingaweb, always get "Fatal error: Call to undefined method Icinga\Application\Config::getSection() in /usr/local/icingaweb/modules/graphite/library/Graphite/Grapher.php on line 28".
Seems that this method is not defined in the Config class. There is no such method in the base class either.

Using icingaweb2 version 2.0.0~rc1~jessie
icingaweb2-module-graphite 0.0.0.1

Regards,

Technikwerner

**Comment by philiphoy** [comment]
I don't think that the config Api has changed so perhaps something else is wrong. Can you confirm that you have added a configuration ini file. It will most likely be at /etc/icingaweb/modules/graphite/config.ini  but may be elsewhere depending on set up. For the correct location see the graphite modules config tab.

**Comment by technik-werner** [comment]
Yes, I've created the config.ini. I've investigated the Config.php file and there is no definition of the method GetSection. I've looked at the base class (Zend_Config) and didn't found this method, too.
Maybe it is some problem with the Zend framework?

config.ini:

```
[graphite]
metric_prefix = icinga
base_url = http://pantograf:8000/render?
```

**Comment by philiphoy** [comment]
The method is here: https://github.com/Icinga/icingaweb2/blob/master/library/Icinga/Application/Config.php#L236
 Also the icinga authored modules use the method:
https://github.com/Icinga/icingaweb2-module-pnp4nagios/blob/master/library/Pnp4nagios/Grapher.php#L27
