### ISSUE TITLE
"-" aren't converted to "_" in this module

### ISSUE THREAD

**Issue by Ziaunys** [philiphoy/icingaweb2-module-graphite#19]
It looks like this module only converts "." to "_" in the Graphite targets.  However, Icinga2 converts both "-" and "." to "_". Is there any way around this?

**Comment by MrCalhoun** [comment]
Edit your "/usr/share/icingaweb2/modules/graphite/library/Graphite/Macro.php" 
and search for "escapeMetric".
Then add the line: "$str=str_replace('-','_',$str);"

It works for me.

**Comment by TheFlyingCorpse** [comment]
I have not seen this behaviour (icinga2 changing - to _ in the current master branch).

**Comment by rp3u** [comment]
hm... it is very strange but
with Icinga2 2.3.10 (last update!) you need to:
1. fall back to $str=str_replace('-','_',$str) in Macro.php
2. put 'legacy_mode = true' in icingaweb2/modules/graphite/config.ini

**Comment by bebehei** [comment]
Hi guys, had the same issue. PR created. Hope the maintainer merging this.

**Comment by philiphoy** [comment]
see https://github.com/findmypast/icingaweb2-module-graphite/commit/511297472ea44182ee242b6c03d978ab768457c8
