### ISSUE TITLE
graphite_keys is always empty for me

### ISSUE THREAD

**Issue by rp3u** [philiphoy/icingaweb2-module-graphite#21]
Grapher.php
        if (array_key_exists("Graphite Keys", $object->customvars))
False always! But keys are look good on the web UI:
Custom Variables
Graphite Keys    rta

Config for host:
    vars.graphite_keys = ["rta"]
Config for service ping4:
    vars.graphite_keys = ["rta"]

**Comment by philiphoy** [comment]
It looks like the following commit changed the behavior: https://github.com/Icinga/icingaweb2/commit/62d96a154eefbff7c80b77d195d6bfa03df5d604. I will change the code in  accordance.

**Comment by philiphoy** [comment]
Fixed as of https://github.com/findmypast/icingaweb2-module-graphite/commit/c9ba65dc2ec64998b375cfb127a4195fc399acbf.
