### ISSUE TITLE
Wrong URL causes "No Data" output

### ISSUE THREAD

**Issue by XmcgX** [philiphoy/icingaweb2-module-graphite#23]
The URL is as follows:

http://servername/graphite/render?&target=icinga2.hostname.rta.value&source=0&width=800&height=700&colorList=049BAF&lineMode=connected&from=-10min

Should be:
http://servername/graphite/render?target=icinga2.hostname.services.ping4.hostalive-ping4.perfdata.rta.value ...

-Icingaweb2 version 2.0.0

**Comment by cgoswami** [comment]
I am having the same issue

version info
icinga2-2.3.10-1.el7.centos.x86_64
icingaweb2-2.0.0-5.el7.centos.noarch

**Comment by sergey-rsa** [comment]
same issue. not working (
any workaround?
in my case icinga2, graphite+grafana
I can see graphs in grafana but not in icingaweb2

**Comment by XmcgX** [comment]
OK it´s an issue of my Icinga2 version. 
My version is v2.3.0-661-ga0631cd.
The url scheme will change in the newer versions.

**Comment by 6bIBAET** [comment]
And what to do?

**Comment by XmcgX** [comment]
Downgrade your icinga2 version (If you use a snapshot, install the released repo (complete uninstallation is required)) or wait until the developer of this modul reacts.

**Comment by 6bIBAET** [comment]
Sadness... 

My version is 2.3.11

**Comment by sorano** [comment]
Another solution for this I found was:

vi /usr/share/icingaweb2/modules/graphite/library/Graphite/Grapher.php
$legacyMode = 'true';

**Comment by 6bIBAET** [comment]
This work for me) Thanks a lot

**Comment by de1m** [comment]
hostname.rta**.**value&source -> Correct is: hostname.rta**&**value&source
you need to change ".value" in "&value" in /usr/share/icingaweb2/modules/graphite/library/Graphite/Grapher.php

**Comment by sorano** [comment]
@de1m 

I'm not following.

You are refering to this file right?
https://github.com/findmypast/icingaweb2-module-graphite/blob/master/library/Graphite/Grapher.php

There is no hostname.rta.value in that file?

Edit, nevermind. I found https://github.com/de1m/icingaweb2-module-graphite/commit/465c68ec6552c8759cdedf8a6ed4d8e9e64e220b

**Comment by XmcgX** [comment]
Try this:
/usr/share/icingaweb2/modules/graphite/library/Graphite/Grapher.php
change the value of $serviceMacro to following : 
protected $serviceMacro = '$HOSTNAME$.services.$SERVICEDESC$.$SERVICEDESC$.perfdata';

Works for me :)

**Comment by de1m** [comment]
@sorano 
yes, I meant this file. Show the line 109, you need to change from ".value" to "&value"

If you show the generated url for graphite image, this is not correct 
With error 
http://servername/graphite/render?&target=icinga2.hostname.rta**.**value&source=0&width=800&height=700&colorList=049BAF&lineMode=connected&from=-10min

without error
http://servername/graphite/render?&target=icinga2.hostname.rta**&**value&source=0&width=800&height=700&colorList=049BAF&lineMode=connected&from=-10min

I've changed "." to "&"

**Comment by sorano** [comment]
@de1m yes I saw your pull request :) :+1: 

It works good now without having to use legacymode = true. Thanks!

**Comment by philiphoy** [comment]
You can set the variable from the config file btw.

**Comment by sorano** [comment]
@philiphoy 

Do you mean the legacymode variable?

I tried setting
legacymode = true (found the error here, the variable name is legacy_mode)

in /etc/icingaweb2/modules/graphite/config.ini before changing it in Grapher.php but I did not get it to work. Maybe I used wrong name for the variable?

Will you merge #25 ?

**Comment by philiphoy** [comment]
Erm i think #25 is at odds with the docs http://docs.icinga.org/icinga2/snapshot/doc/module/icinga2/chapter/advanced-topics

**Comment by philiphoy** [comment]
Also perhaps your config is in the wrong location. The correct location can be checked by going to icingaweb->system->module->graphite->config, there you should see an example config.

**Comment by cgoswami** [comment]
@philiphoy i am facing similar issue as @sorano my graphs are working with #25 and legacy_mode variable commented, the path for config for the all the other modules in Centos 7 defaults to /etc/icingaweb2/modules/graphite/config.ini, although i  do agree i am missing some info here and am confused about legacy_mode var, could you tell what it defaults to when its commented out ?

**Comment by sorano** [comment]
@philiphoy 

I took some more time to test this.
My file is in the correct location according to Configuration -> Modules.
(also Grapher.php was restored to default)

apache2 -v
Server version: Apache/2.4.10 (Debian)
Server built:   Aug 28 2015 16:28:08

So if I copy the contents of the example from Configuration -> Modules -> Graphite -> Configuration as such (replacing to match my prefix and url):

```
[graphite]
metric_prefix = icinga
base_url = http://mysecreturl.tld:8000/render?
legacy_mode = false
;if legacy mode is false (2.4 and newer):
service_name_template = "$host.name$.services.$service.name$.$service.check_command$.perfdata"
host_name_template = "$host.name$.host.$host.check_command$.perfdata"
;if legacy mode is true (pre 2.4):
;service_name_template = "$host.name$.services.$service.name$.$service.check_command$"
;host_name_template = "$host.name$.host.$host.check_command$"
;this template is used for the small image, macro $target$ can used.
graphite_args_template = "&target=$target$&source=0&width=300&height=120&hideAxes=true&lineWidth=2&hideLegend=true&colorList=049BAF"
;this template is used for the large image, macro $target$ can used. 
;graphite_large_args_template = "&target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=800&height=700&colorList=049BAF&lineMode=connected"    
```

and place this in config.ini I get instant "No Data" on my graphs.

However if I edit the following lines to

```
legacy_mode = true 
and comment this line
#host_name_template = "$host.name$.host.$host.check_command$.perfdata"
```

Then my graphs show as normal.

Somehow it feels reversed, in my case legacy_mode should not be needed. Yet it is the only thing that I get to work.

However if I apply #25 I can use 

legacy_mode = false

but I still need to comment out
#host_name_template = "$host.name$.host.$host.check_command$.perfdata"

@cgoswami by default legacy_mode is set to false as defined on line 25 in
https://github.com/findmypast/icingaweb2-module-graphite/blob/master/library/Graphite/Grapher.php

**Comment by de1m** [comment]
@sorano 
This is my config.ini
[graphite]
metric_prefix = icinga
base_url = http://graphite.host/render?
service_name_template = "$host.name$.$service.name$"
host_name_template = "$host.name$"
;this template is used for the small image, macro $target$ can used.
graphite_args_template = "&target=$target$&source=0&width=300&height=120&hideAxes=true&lineWidth=2&hideLegend=true&colorList=049BAF"

and its working with [#25](https://github.com/findmypast/icingaweb2-module-graphite/pull/25)

**Comment by sorano** [comment]
@de1m 
Thanks but if #25 will not be merged I would prefer a solution without using it ;)

So for now I will leave Grapher.php at default and continue with config.ini as such:

```
[graphite]
metric_prefix = icinga
base_url = http://graphite.host/render?
legacy_mode = true

;this template is used for the small image, macro $target$ can used.
graphite_args_template = "&target=$target$&source=0&width=300&height=120&hideAxes=true&lineWidth=2&hideLegend=true&colorList=049BAF"
;this template is used for the large image, macro $target$ can used.
graphite_large_args_template = "&target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=800&height=700&colorList=049BAF&lineMode=connected"
```

The *_name_template seems to not be needed for me in config.ini since it works without them.

**Comment by cgoswami** [comment]
thanks @sorano and your config file and comments explain alot of what i was missing, i am gonna do build with master and test with commented line

#host_name_template = "$host.name$.host.$host.check_command$.perfdata"

will  update the results of my tests

**Comment by sergey-rsa** [comment]
config.ini 
service_name_template = "$host.name$.$service.name$"
thanks!
