### ISSUE TITLE
translateTerm function

### ISSUE THREAD

**Issue by totosh** [philiphoy/icingaweb2-module-graphite#24]
I use custom graphite template like this : 

<pre>
host_name_template = "$host.vars.location$.$host.vars.zone$.$host.vars.env$.$host.name$"
service_name_template = "$host.vars.location$.$host.vars.zone$.$host.vars.env$.$host.name$.$service.vars.type$.$service.vars.subtype$.$service.name$"
</pre>

I obtain these errors 

<pre>2015-10-14T17:58:06+02:00 - ERROR - ErrorException in /var/www/icingaweb2/modules/graphite/library/Graphite/Macro.php:102 with message: Undefined variable: cv
2015-10-14T17:58:06+02:00 - ERROR - Stacktrace: #0 /var/www/icingaweb2/modules/graphite/library/Graphite/Macro.php(102): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined varia...', '/var/www/icinga...', 102, Array)
#1 /var/www/icingaweb2/modules/graphite/library/Graphite/Macro.php(72): Icinga\Module\Graphite\Macro::translateTerm('host.vars.locat...')
#2 /var/www/icingaweb2/modules/graphite/library/Graphite/Macro.php(36): Icinga\Module\Graphite\Macro::resolveMacro('host.vars.locat...', Object(Icinga\Module\Monitoring\Object\Host))
#3 /var/www/icingaweb2/modules/graphite/library/Graphite/Grapher.php(99): Icinga\Module\Graphite\Macro::resolveMacros('$host.vars.loca...', Object(Icinga\Module\Monitoring\Object\Host), 'false')
</pre>

If i edit /var/www/icingaweb2/modules/graphite/library/Graphite/Macro.php

<pre>
if (substr($term, 0, strlen('host.vars.')) === 'host.vars.'){
  $term = str_replace('host.vars.','',$term);
  return ucwords(str_replace('_', ' ', strtolower($cv->varname)));
}
if (substr($term, 0, strlen('service.vars.')) === 'service.vars.'){
  $term = str_replace('service.vars.','',$term);
  return ucwords(str_replace('_', ' ', strtolower($cv->varname)));
}
</pre>

by 

<pre>
if (substr($term, 0, strlen('host.vars.')) === 'host.vars.'){
 return str_replace('host.vars.','',$term);
}
if (substr($term, 0, strlen('service.vars.')) === 'service.vars.'){
  return str_replace('service.vars.','',$term);
}
</pre>

Module works but i've others errors. Module not revolve "$host.vars.XXX" macros on the  service_name_template variable.

<pre>
2015-10-14T18:05:47+02:00 - ERROR - Icinga\Exception\InvalidPropertyException in /var/www/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php:770 with message: Can't access property 'location'. Property does not exist.
2015-10-14T18:05:47+02:00 - ERROR - Stacktrace: #0 /var/www/icingaweb2/modules/graphite/library/Graphite/Macro.php(78): Icinga\Module\Monitoring\Object\MonitoredObject->__get('location')
#1 /var/www/icingaweb2/modules/graphite/library/Graphite/Macro.php(36): Icinga\Module\Graphite\Macro::resolveMacro('host.vars.locat...', Object(Icinga\Module\Monitoring\Object\Service))
</pre>

**Comment by philiphoy** [comment]
Removed the ucwords call 169ae7b

**Comment by opstfa** [comment]
Hi,

I'm also running a distributed setup, using host.vars.location in host_name_template and service_name_template. It works fine for host graphs but not for service graphs.
Getting the same error as totosh: Can't access property 'location'. Property does not exist.
It does work if you add the location variable to the service as well, but that's not really on option : )

Thanks!
