### ISSUE TITLE
Error after update to icinga2 2.4

### ISSUE THREAD

**Issue by astrandb** [philiphoy/icingaweb2-module-graphite#31]
After changing legacymode to false I got "No Data" message on all host/services that contain a '-' in the name.
I found that the escapeMetric function does escape '-' regardless of the legacyMode setting.
When I change "if ($legacyMode)" to "if ($legacyMode == 'true') it works properly. I don't know if this is the proper way to fix the problem but it works for me.

**Comment by philiphoy** [comment]
see #30

**Comment by philiphoy** [comment]
See #30. should be resolved soon.

**Comment by hk298** [comment]
Another issue with Icinga 2.4 is the new Graphite [schema](https://www.icinga.org/2015/11/09/icinga-2-v2-4-new-graphite-schema/) that doesn't seem to be supported yet.
In Macro.php we need a new macro:

```
    'CHECKCOMMAND' => 'check_command'
```

and in Grapher.php we would need different host and service macros:

```
    protected $serviceMacro = '$HOSTNAME$.services.$SERVICEDESC$.$CHECKCOMMAND$.perfdata';
    protected $hostMacro = '$HOSTNAME$.host.$CHECKCOMMAND$.perfdata';
```

However, these should be options because in Icinga you have the choice of continuing to use the old schema.

**Comment by Alex9779** [comment]
Well as far as I can see those macros are obsolete anyway. You can use the macros provided by Icingaweb2.
Look at the demo config in /application/views/scripts/config/index.phtml:

```
service_name_template = "$host.name$.services.$service.name$.$service.check_command$.perfdata"
host_name_template = "$host.name$.host.$host.check_command$.perfdata"
```

it does right that...

BTW in that file there are the templates for the old format too and those do not use the macros from Macro.php either...

**Comment by Alex9779** [comment]
BTW in that file there are the templates for the old format too...

**Comment by philiphoy** [comment]
Thanks to @Alex9779 the original issue is now resolved. If there are other problems please raise a separate issue.
