### ISSUE TITLE
"value," "crit" and "warn"

### ISSUE THREAD

**Issue by hk298** [philiphoy/icingaweb2-module-graphite#32]
The current Grapher.php appends '.value' to $target if legacyMode == false. The graphite_large_args_template then appends '_crit' and '_warn', so we end up with $target$.value_crit. This doesn't work because icinga 2.4 uses $target$.crit.

Maybe Grapher.php should never append '.value'. This can be done by the templates.

**Comment by philiphoy** [comment]
Good call @hk298, It would indeed make sense to move value out to the template, also Grapher ->metricPrefix  has become somewhat redundant too.
Do you fancy sending a pull request for that?

**Comment by hk298** [comment]
@philiphoy I'd rather leave that to someone who knows the code and github.

**Comment by philiphoy** [comment]
@hk298 Fair enough i will take it on as as it needs sorting. That said os is fun and i would be happy to help you out if you want. I am sure you would find it easier than you think.

**Comment by philiphoy** [comment]
Done as of 515fa97a9e10860fc1d8bfd0ea9e747855fccd9f
