### ISSUE TITLE
Error in service_name_template

### ISSUE THREAD

**Issue by cbirkenbeul** [philiphoy/icingaweb2-module-graphite#38]
I just upgraded icinga2 to 2.4 and updated your graphite module. But i do not see any graphes. If i have a look at the url i see that there is a twist:
Current:
http://url/icingaweb2/graphite?graphite_url=http%253A%252F%252Furl%252Frender%252F%253F%2526target%253Dicinga2.icinga_kernarea_de.services.load.load.perfdata.value.load1
Schould be:
http://url/icingaweb2/graphite?graphite_url=http%253A%252F%252Furl%252Frender%252F%253F%2526target%253Dicinga2.icinga_kernarea_de.services.load.load.perfdata.load1.value

The twist is in the last two values. First the perfdate value dann value

icinga2.url.services.load.load.perfdata.load5.value

**Comment by ghost** [comment]
I'm having the same problem.
