### ISSUE TITLE
Wrong URL for disk graph

### ISSUE THREAD

**Issue by rustyricky** [philiphoy/icingaweb2-module-graphite#43]
Hi,

I have an issue with the disk graph.

The URL of the embedded graph in icingaweb2 is:
`target=host_com.services.disk__.disk.perfdata._.value`

By looking through the graphiteweb interface I found the correct URL should be:
`target=host_com.services.disk__.disk.perfdata./.value`

Any way to modify this url?

**Comment by AdamNuclear** [comment]
Hi, same issue here: 

![image](https://cloud.githubusercontent.com/assets/12887311/11460122/ef0e273a-96e6-11e5-9277-d4c3a47442b8.png)

actual url: icinga2.host.services.disk__.dummy.perfdata./.value

should be: icinga2.host.services.disk__.dummy.perfdata._.value

**Comment by ghost** [comment]
Hi， I have same issue，but I fixed

at line 107 in graphite/library/Graphite/Grapher.php

$target = Macro::resolveMacros($target, array("metric"=>$metric), $this->legacyMode, false);
change to
$target = Macro::resolveMacros($target, array("metric"=>$metric), $this->legacyMode, true);
or
$target = Macro::resolveMacros($target, array("metric"=>$metric), $this->legacyMode);

**Comment by philiphoy** [comment]
closed #42
