### ISSUE TITLE
metrics containing space won't be shown

### ISSUE THREAD

**Issue by shivan** [philiphoy/icingaweb2-module-graphite#44]
In current version 0.0.0.4 in combination with icinga2 2.4 when a metric contains a space, this won't be shown.

For example "committed" will be shown, but the metric "committed %" won't be shown. (Example with ram check)

**Comment by philiphoy** [comment]
does #42 not fix that?

**Comment by shivan** [comment]
Yes, Tried again that version.. seems the solution overlapped... I pushed my change 2h after you accepted the merge request. So I'll close.
