### ISSUE TITLE
str_replace('.','_',$str) crashes metric

### ISSUE THREAD

**Issue by chaosben** [philiphoy/icingaweb2-module-graphite#46]
In my case the metric is named "icinga2.max.services.PSU-Load.snmp.perfdata.FSC-SERVERCONTROL2-MIB.sc2psPowerSupplyLoad.1.1.value".
But the function "escapeMetric" converts it to "icinga2.max.services.PSU-Load.snmp.perfdata.FSC-SERVERCONTROL2-MIB.sc2psPowerSupplyLoad_1_1.value" which results in an "NoData"-Graph.

Is it my fault or can you fix it?

**Comment by philiphoy** [comment]
Ah it looks like the graphite writer escapes dots (.) in the prefix part of the target name but not the metric part. Of course this module needs to follow suit.

**Comment by philiphoy** [comment]
fixed with c4082b09a2aa00f1de74ea04f763c3e5334d223f

**Comment by chaosben** [comment]
Well done. Thank you!
