### ISSUE TITLE
Can't view the old graphs (10 minutes, 1 hour, 12 hours) in icingaweb2.

### ISSUE THREAD

**Issue by AbdullahKh** [philiphoy/icingaweb2-module-graphite#48]
Hello,

I was trying to use this nice module, but I had a small issue!

![icingaweb2-1](https://cloud.githubusercontent.com/assets/4739442/12538575/0e74f4c2-c2ee-11e5-837c-cc1980ecdc38.png)

I can't use the upper menu which shows the old graphs! for example the previous 10 minutes.
Whenever I click on any of the time periods I get this!

![icingaweb2-2](https://cloud.githubusercontent.com/assets/4739442/12538570/ef7d0d48-c2ed-11e5-8344-3b52d263cc44.png)

Although when I tried to open the page (10 minutes) in a new tap it worked fine!

![icingaweb2-3](https://cloud.githubusercontent.com/assets/4739442/12538572/fe4ed856-c2ed-11e5-9fbb-a240c1baadb7.png)

Configuration files are as follow:

/etc/icingaweb2/modules/graphite/config.ini

> [graphite]
> metric_prefix = icinga2
> base_url = /render?
> legacy_mode = false
> ;if legacy mode is false (2.4 and newer):
> service_name_template = "icinga2.$host.name$.services.$service.name$.$service.check_command$.perfdata.$metric$.value"
> host_name_template = "icinga2.$host.name$.host.$host.check_command$.perfdata.$metric$.value"
> ;if legacy mode is true (pre 2.4):
> ;service_name_template = "icinga.$host.name$.services.$service.name$.$service.check_command$"
> ;host_name_template = "icinga.$host.name$.host.$host.check_command$"
> ;this template is used for the small image, macro $target$ can used.
> graphite_args_template = "&target=$target$&source=0&width=300&height=120&hideAxes=true&lineWidth=2&hideLegend=true&colorList=049BAF"
> ;this template is used for the large image, macro $target$ can used.
> ;graphite_large_args_template = "&target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=800&height=700&colorList=049BAF&lineMode=connected"

/etc/carbon/storage-schemas.conf

> [carbon]
> pattern = ^carbon.
> retentions = 60:90d
> [icinga]
> pattern = ^icinga*.
> retentions = 60:90d
> # retentions = 10s:10m,1m:1h,10m:1d
> 
> [default_1min_for_1day]
> pattern = .*
> retentions = 60s:1d

Thanks in advance

**Comment by philiphoy** [comment]
Use an absolute url for the base_url  ie. http://graphite.server.com/render?
