### ISSUE TITLE
Selecting Time Period above 1 week

### ISSUE THREAD

**Issue by toxicvengeance** [philiphoy/icingaweb2-module-graphite#50]
Hi,

I have a problem when selecting a time period of more then 1 week. When pressing the 1 month or 1 year option the 1 week graph appears. I already posted about this in the monitoring-portal.org and someone else seems to have the same issue. Does anyone know what I could do to fix this ?
I am using the latest version of the graphite plugin for icingaweb2(also latest version).

My storage-schemas config looks like this:

`[carbon]
pattern = ^carbon\.
retentions = 60:90d
[icinga_internals]
pattern = ^icinga\..*\.(max_check_attempts|reachable|current_attempt|execution_time|latency|state|state_type)
retentions = 5m:7d
[icinga_default]
pattern = ^icinga\.
retentions = 5m:10d,30m:90d,360m:4y`

https://monitoring-portal.org/index.php?thread/35330-icingaweb2-graphite-zeitspannenauswahl/

**Comment by philiphoy** [comment]
Perhaps you need to change the retention for: 

`pattern = ^icinga\..*\.(max_check_attempts|reachable|current_attempt|execution_time|latency|state|state_type)`

At the moment it is only 1 week (5m:7d) so will only ever show a maximum of 1 weeks worth of metrics.

**Comment by ghost** [comment]
Hi,

Also changed that a few times but it doesnt change anything. That pattern is only for Icinga2 internal stuff i think.

**Comment by philiphoy** [comment]
The graphite whisper file is fixed size and will use whatever the configuration is when it is first created, updating the configuration afterwards will not change any files already on disc. See http://graphite.readthedocs.org/en/latest/config-carbon.html#storage-schemas-conf 
You can however resize the file after the fact using whisper-resize.py .
