### ISSUE TITLE
can't get composit graphs working

### ISSUE THREAD

**Issue by keulator** [philiphoy/icingaweb2-module-graphite#53]
Hi,

I don't know if this is relate to another issue, but I can't get composit graphs working. To me it looks like vars.graphite_keys settings in icinga2 services is totally ignored.

I tried the following setting according to documentation:

vars.graphite_keys = [ "{load1,load5,load15}" ]

From my understanding I should get 1 graph with 3 lines, but I keep getting 3 individual graphs - or am I understanding somethig wrong here ?

Even, if I try to just graph f.e. just load1 and load5 all 3 values are graphed.

I am using icinga2 2.4.7, icingaweb2 2.3.2 as well as icingaweb2-module-graphite 0.0.0.5 on debian jessie.

Any help would be appreciated.

**Comment by p0nts** [comment]
me neither, neither can I get the limit working:

  vars.graphite_keys = ["load1", "load5"]

EDIT:

They do show as custom variables:

Custom Variables
Graphite Keys  
{load1,load15}

**Comment by p0nts** [comment]
update:

it does show as variables:
https://www.dropbox.com/s/r7kdntog1vja0c1/Screenshot%202016-05-18%2010.47.23.png?dl=0

What is going wrong?

**Comment by usmanatron** [comment]
Note: a workaround to get graphite_keys etc. working is to manually edit Grapher.php and edit one line.  I've raised a pull request for this (https://github.com/findmypast/icingaweb2-module-graphite/pull/61) but just in case you're keen to get this working :-)
