### ISSUE TITLE
not all graphs working in version 2.3.4-1

### ISSUE THREAD

**Issue by DoGlatemLive** [philiphoy/icingaweb2-module-graphite#58]
Hi, 

I recently found an issue where the bigger pictures of the graphs are not working properly.

When I use icingaweb2 version 2.3.2-1 with icinga2 version 2.4.8-1, everything works fine.

However, with version 2.3.4-1 of icingaweb2 the bigger ones are not getting loaded(see attachment).

The request the same URL and also the config of both is quiet the same.

Cheers,

Mike
![graph issue](https://cloud.githubusercontent.com/assets/20225208/16489268/0cd0888a-3ed5-11e6-873d-cd75b5005725.PNG)

**Comment by dmytro-rusakov** [comment]
Hello! I have the same issue
Is there any progress or solution?
UPD: for me the solution was to set header in graphite site, that allows iFrame:
Header always set X-Frame-Options "ALLOW-FROM http://your_icinga"

**Comment by DoGlatemLive** [comment]
Posted this long ago. I think this was also the solution for me. 
Closing issue.
