### ISSUE TITLE
Diffrent perfdata labels in graphite and icingaweb2

### ISSUE THREAD

**Issue by RayMisterio** [philiphoy/icingaweb2-module-graphite#64]
hi guys,

if got a confusing problem with the prefdata labels in graphite and icingaweb2.

in icingaweb2 the prefdata label calls **_total_** and in graphte it calls **_total=123039MB;used_**
thats why to diffrent URLs exist.

Graphite creates this one:
http://localhost/render/?width=586&height=308&target=icinga2.blade10.services.RAM_usage.nrpe_check.perfdata.**_total%3D129039MB%3Bused_**.value

And icingaweb2 refers to 

http://localhost/render/?&width=300&height=120&target=icinga2.blade10.services.RAM_usage.nrpe_check.perfdata.**_total_**.value

Is this a problem of graphite or of the storge by icinga2?

**Comment by sbancal** [comment]
Perf data has to be separated by a space, not an ';'. It's the check that doesn't produce the output that is parsed correctly after.
See https://www.monitoring-plugins.org/doc/guidelines.html#AEN201 for Performance data rules.
