### ISSUE TITLE
New user role graphite graphs not showing

### ISSUE THREAD

**Issue by Klar** [philiphoy/icingaweb2-module-graphite#66]
If I set in icingaweb2 a role which does not have "Allow everything(*)" the graphite graphs are not showing. If the role has the permission "Allow Everything" the graphs work.

I tried to fix / search the issue by myself but couldn't find the correct line.

thanks for having a look.

**Comment by rajo** [comment]
cf. https://dev.icinga.com/issues/13721
seems to be related to the lines

    old code: $this->registerHook('grapher', '\\Icinga\\Module\\Graphite\\Grapher');
    new code: $this->registerHook('grapher', 'Icinga\\Module\\Graphite\\Grapher');

I can confirm this issue - if the above fix is applied, the settings in /etc/icingaweb2/roles.ini (permissions = ".... module/grarphite ... ") take effect. Without this fix, the graphs are only showing when "Allow everything(*)" is set.

**Comment by Klar** [comment]
Thanks, manually change seems to fix the issue.

**Comment by Klar** [comment]
Thank you. It's working after the manual change.
