### ISSUE TITLE
Config.ini in wrong directory

### ISSUE THREAD

**Issue by mipapo** [philiphoy/icingaweb2-module-graphite#7]
To install a module you have to put the module in /usr/share/icingaweb/modules/.
In the "Configuration" tab of the module it tells you to put the config file to: "/etc/icingaweb/modules/graphite/config.ini"
Thats fine, but then I have the config.ini in /etc/icingaweb/modules/graphite and the module in /usr/share/icingaweb/modules ...
Is that the idea of the icingaweb module system?

**Comment by philiphoy** [comment]
I just copied the same convention as used in an https://github.com/Icinga/icingaweb2-module-pnp4nagios which is an icinga authored module. Tbh i could not say for sure whether it is the appropriate location though as the icingaweb2 documentation is scant in this regard.
