### ISSUE TITLE
Metric Names

### ISSUE THREAD

**Issue by markvr** [philiphoy/icingaweb2-module-graphite#8]
Hi,  thanks for this, it looks really useful.  

One issue/question is that it replaces the dots with underscores in the target for rendering. 
i.e. my graphite server needs: http://graphite-server.local/render?&target=sysdev-icinga.prod.host.tcw_p18.rta
But this generates:
http://graphite-server.local/render?&target=sysdev-icinga.prod_host_tcw_p18.rta
which fails.

My Icinga graphite.conf is:
 host_name_template = "sysdev-icinga.$host.vars.env$.host.$host.vars.shortname$"
  service_name_template = "sysdev-icinga.$host.vars.env$.$host.vars.type$.$host.vars.shortname$.$service.name$"

So this is presumably why, i.e. I'm not using the default naming scheme.

Is there anyway this module can either read this config, or have the ability to define this in it's own config?  I'd love to use this, I just can't at the moment!

**Comment by markvr** [comment]
Alternatively - and probably easier - how about having something similar to "vars.graphite_keys" but where the value supplied is taken literally as the full name of the metric?  i.e. doesn't have anything pre/appended to it?

**Comment by philiphoy** [comment]
Hi @markvr, i have added macro resolution so you can now configure host_name_template = "sysdev-icinga.$host.vars.env$.host.$host.vars.shortname$" however the implementation is not the same as that used in the graphite writer so it could well fail for some expressions.

**Comment by philiphoy** [comment]
@philiphoy

**Comment by tommyorndorff** [comment]
This causes all snmp checks to fail in rendering data.

**Comment by markvr** [comment]
Hi thanks for adding this!

Unfortunately I'm having a problem:  On the "services" page I get the error:
`"Can't access property 'graphite_1'. Property does not exist."`

My config.ini for this is:

```
service_name_template = "$service.vars.graphite_1$.$service.vars.graphite_2$.$service.vars.graphite_3$.$service.vars.graphite_4$.$service.vars.graphite_5$.$service.hostshortname$"
```

And an example service is:

```
object Service "webfarm/webapp/accom" {
     check_command = "http"
...<snip>...
     vars.graphite_1 = "webfarm"
     vars.graphite_2 = "webapp"
     vars.graphite_3 = "accom"
     vars.graphite_4 = "_"
     vars.graphite_5 = "_"
}
```

Have I done something wrong?!

**Comment by markvr** [comment]
Investigating further, if I dump the object out from PHP in Macro.php, the only reference to my vars.graphite_1=".." is in $object->customvars, but they have had some weird altering, so "vars.graphite_1" has become "Graphite 1" which is somewhat unexpected.

The line `if  ($object->{$translated} !== false) {` seems to throw an error if `$translated` doesn't exist, rather than returning false like I imagine is expected.  This is the cause of the `Can't access property` error above.

Icinga  / Icingaweb is presumably silently rewriting the variable names to make them more "readable", which is entirely unhelpful when trying to reference them here!

**Comment by philiphoy** [comment]
@markvr ok now the code does the same weird var name translation which should hopefully fix your issue.
