### ISSUE TITLE
URL doesnt have escaped periods in metric?

### ISSUE THREAD

**Issue by tommyorndorff** [philiphoy/icingaweb2-module-graphite#9]
Hey there,

Sorry, I apologize if this is obvious.  I have snmp checks sending data to graphite.  The snmp check switches the OID into something that looks like this kind of graphite metric string: `icinga.<hostname>.<service>.iso_3_6_1_4_1_9_9_48_1_1_1_6_1`

I see on line 100 of Grapher.php (`$target .= '.'. Macro::escapeMetric($metric, true);`) and the code that should be switching out the periods for underscores, but I cant figure out the logical reason for the `if (!$isMetric)` block.  

In what scenario would we not want to have periods escaped in the $metrics variable?

``` php
    public static function escapeMetric($str, $isMetric)
    {
        if (!$isMetric)
        {
            $str=str_replace('.','_',$str);
        }
        $str=str_replace(' ','_',$str);
        $str=str_replace('-','_',$str);
        $str=str_replace('\\','_',$str);
        $str=str_replace('/','_',$str);
        return $str;
    }
```

**Comment by philiphoy** [comment]
@tommyorndorff I think that logic is a hang over from before my attempt to use macro's to define the keys. I will remove it and push.

**Comment by philiphoy** [comment]
done
